FPS = 60
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1366, 768
SCREEN_CENTER = SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2
POINTS_TOPRIGHT_POS = SCREEN_WIDTH - SCREEN_HEIGHT // 64, SCREEN_HEIGHT // 64

CURSOR_FILENAME = 'cursor20alt.png'

SOUND_VOLUME = 0.2
