FPS = 60
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1366, 768
SCREEN_CENTER = SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2

OFFSET = SCREEN_HEIGHT // 64
POINTS_TOPRIGHT_POS = SCREEN_WIDTH - OFFSET, OFFSET

CURSOR_FILENAME = "cursor20alt.png"
FONT_PATH = "source/fonts/PerfectDOSVGA437.ttf"
FONT_SIZE = 32

SOUND_VOLUME = 0.2
